export const Screen = {
  SPLASH: 'Splash',
  BANNER1: 'Banner1',
  BANNER2: 'Banner2',
  BANNER3: 'Banner3',
  WELCOME: 'Welcome',
  LOGIN: 'LogIn',
  OTP: 'Otp',
  HOME: 'Home',
  LANGUAGE: 'Language',
  PROFILE: 'Profile',
  BANNERFIRST:'Bannerfirst',
  BANNERSECOND:'Bannersecond',
  BANNERTHIRD:'Bannerthird',
  BANNERFOURTH:'Bannerfourth',
  ONBOARDINGCONTAINER:'Onboardingcontainer',
  OTPVERIFICATION:'Otpverification',
  CREATENEWKUNDALI:'Createnewkundali',
  SIMILERASTROLOGR:'Similarastrologer',
  BASICDETAILS:'Basicdetails'
};
